export const ipfsUrl = 'https://gateway.pinata.cloud/ipfs/';
export const tickets = [
  {
    id: '4cCuxGrhmw1_ccYnuOIXk',
    name: 'Los Angeles Lakers',
    date: '2022-03-28T22:22',
    image: 'QmfQrwm7PhRVNZrEVzdef39RD4fyjZroJ5sj6n9hLfB8Ga',
    ticketsSold: 45,
    ticketsCount: 500,
    eventDetails: [
      { ticketType: 'Vip', ticketCount: 100, ticketPrice: 400 },
      { ticketType: 'General', ticketCount: 100, ticketPrice: 50 },
      { ticketType: 'Bussiness', ticketCount: 100, ticketPrice: 200 },
      { ticketType: 'General Admission', ticketCount: 100, ticketPrice: 200 },
    ],
  },
  {
    id: '4cCuxGrhmw1_ccYnuOIXk',
    name: 'Coachella 2022',
    date: '2022-03-28T22:22',
    image: 'QmfUkXyisB3PHAxzqFeRVp6JQisz5T5fGMAzzyocsEh6QL',
    ticketsSold: 905,
    ticketsCount: 5000,
    eventDetails: [
      { ticketType: 'Vip', ticketCount: 100, ticketPrice: 400 },
      { ticketType: 'General', ticketCount: 100, ticketPrice: 50 },
      { ticketType: 'Bussiness', ticketCount: 100, ticketPrice: 200 },
      { ticketType: 'General Admission', ticketCount: 100, ticketPrice: 200 },
    ],
  },
  {
    id: 'ZnJ8MnhrMlYMkFcJk_pJP',
    name: 'Avril Lavigne Bite Me Canada Tour 2022 with Modsun',
    date: '2022-03-28T22:22',
    image: 'QmZc8BMXPTd1Jh2jkNGPKtEWhtrjK6Dy6328AipQLcKvRt',
    ticketsSold: 45,
    ticketsCount: 500,
    eventDetails: [
      { ticketType: 'Vip', ticketCount: 100, ticketPrice: 400 },
      { ticketType: 'General', ticketCount: 100, ticketPrice: 50 },
      { ticketType: 'Bussiness', ticketCount: 100, ticketPrice: 200 },
      { ticketType: 'General Admission', ticketCount: 100, ticketPrice: 200 },
    ],
  },
  {
    id: 'fb8ApBtpIY1Ik9d62ZqFS',
    name: 'After Hours Till Dawn Tour',
    date: '2022-03-28T22:22',
    image: 'QmWsQ4GgvxkeVEjgQ31ynZuqtx7b7DE9hPMHbzCJJN5mcy',
    ticketsSold: 45,
    ticketsCount: 500,
    eventDetails: [
      { ticketType: 'Vip', ticketCount: 100, ticketPrice: 400 },
      { ticketType: 'General', ticketCount: 100, ticketPrice: 50 },
      { ticketType: 'Bussiness', ticketCount: 100, ticketPrice: 200 },
      { ticketType: 'General Admission', ticketCount: 100, ticketPrice: 200 },
    ],
  },
  {
    id: 'J7NrtjDWJnXcbbVfTn7iG',
    name: 'Monster Jam',
    date: '2022-03-28T22:22',
    image: 'QmPVdPutqiNyJjd74eVpnfwUV4XZKLZBbBpyKqqDmampFy',
    ticketsSold: 45,
    ticketsCount: 500,
    eventDetails: [
      { ticketType: 'Vip', ticketCount: 100, ticketPrice: 400 },
      { ticketType: 'General', ticketCount: 100, ticketPrice: 50 },
      { ticketType: 'Bussiness', ticketCount: 100, ticketPrice: 200 },
      { ticketType: 'General Admission', ticketCount: 100, ticketPrice: 200 },
    ],
  },
];

export const activeTicket = {
  id: 'J7NrtjDWJnXcbbVfTn7iG',
  name: 'Monster Jam',
  date: '2022-03-28T22:22',
  image: 'QmPVdPutqiNyJjd74eVpnfwUV4XZKLZBbBpyKqqDmampFy',
  ticketType: 'Vip',
  ticketCount: 100,
  ticketPrice: 400,
};

export const checkInCards = [
  {
    id: '4cCuxGrhmw1_ccYnuOIXk',
    name: 'Los Angeles Lakers',
    date: '2022-03-28T22:22',
    image: 'QmfQrwm7PhRVNZrEVzdef39RD4fyjZroJ5sj6n9hLfB8Ga',
    ticketType: 'Vip',
    ticketPrice: 400,
  },
  {
    id: '4cCuxGrhmw1_ccYnuOIXk',
    name: 'Coachella 2022',
    date: '2022-03-28T22:22',
    image: 'QmfUkXyisB3PHAxzqFeRVp6JQisz5T5fGMAzzyocsEh6QL',
    ticketType: 'Bussiness',
    ticketPrice: 200,
  },
  {
    id: 'ZnJ8MnhrMlYMkFcJk_pJP',
    name: 'Avril Lavigne Bite Me Canada Tour 2022 with Modsun',
    date: '2022-03-28T22:22',
    image: 'QmZc8BMXPTd1Jh2jkNGPKtEWhtrjK6Dy6328AipQLcKvRt',
    ticketType: 'General Admission',
    ticketPrice: 200,
  },
  {
    id: 'fb8ApBtpIY1Ik9d62ZqFS',
    name: 'After Hours Till Dawn Tour',
    date: '2022-03-28T22:22',
    image: 'QmWsQ4GgvxkeVEjgQ31ynZuqtx7b7DE9hPMHbzCJJN5mcy',
    ticketType: 'Vip',
    ticketPrice: 400,
  },
  {
    id: 'J7NrtjDWJnXcbbVfTn7iG',
    name: 'Monster Jam',
    date: '2022-03-28T22:22',
    image: 'QmPVdPutqiNyJjd74eVpnfwUV4XZKLZBbBpyKqqDmampFy',
    ticketType: 'General',
    ticketPrice: 50,
  },
];
