export const tickets = [
  {
    id: '4cCuxGrhmw1_ccYnuOIXqrk',
    name: 'Los Angeles Lakers',
    date: '2022-03-28T22:22',
    image: 'QmfQrwm7PhRVNZrEVzdef39RD4fyjZroJ5sj6n9hLfB8Ga',
    ticketsSold: 0,
    ticketsCount: 40,
    eventDetails: [
      { ticketType: 'Vip', ticketCount: 4, ticketPrice: 1 },
      { ticketType: 'General', ticketCount: 6, ticketPrice: 1 },
      // { ticketType: 'Bussiness', ticketCount: 10, ticketPrice: 1 },
      // { ticketType: 'General Admission', ticketCount: 20, ticketPrice: 1 },
    ],
  },
  // {
  //   id: '4cCuxGrhmw1_ccYnuOIXkfdf',
  //   name: 'Coachella 2022',
  //   date: '2022-03-28T22:22',
  //   image: 'QmfUkXyisB3PHAxzqFeRVp6JQisz5T5fGMAzzyocsEh6QL',
  //   ticketsSold: 0,
  //   ticketsCount: 40,
  //   eventDetails: [
  //     { ticketType: 'Vip', ticketCount: 4, ticketPrice: 1 },
  //     { ticketType: 'General', ticketCount: 54, ticketPrice: 1 },
  //     { ticketType: 'Bussiness', ticketCount: 10, ticketPrice: 1 },
  //     { ticketType: 'General Admission', ticketCount: 20, ticketPrice: 1 },
  //   ],
  // },
  // {
  //   id: 'ZnJ8MnhrMlYMkFcJ323k_pJP',
  //   name: 'Avril Lavigne Bite Me Canada Tour 2022 with Modsun',
  //   date: '2022-03-28T22:22',
  //   image: 'QmZc8BMXPTd1Jh2jkNGPKtEWhtrjK6Dy6328AipQLcKvRt',
  //   ticketsSold: 0,
  //   ticketsCount: 40,
  //   eventDetails: [
  //     { ticketType: 'Vip', ticketCount: 4, ticketPrice: 400 },
  //     { ticketType: 'General', ticketCount: 6, ticketPrice: 50 },
  //     { ticketType: 'Bussiness', ticketCount: 10, ticketPrice: 200 },
  //     { ticketType: 'General Admission', ticketCount: 20, ticketPrice: 200 },
  //   ],
  // },
  // {
  //   id: 'fb8ApBtpIY1Ik9d6ds2ZqFS',
  //   name: 'After Hours Till Dawn Tour',
  //   date: '2022-03-28T22:22',
  //   image: 'QmWsQ4GgvxkeVEjgQ31ynZuqtx7b7DE9hPMHbzCJJN5mcy',
  //   ticketsSold: 0,
  //   ticketsCount: 40,
  //   eventDetails: [
  //     { ticketType: 'Vip', ticketCount: 14, ticketPrice: 400 },
  //     { ticketType: 'General', ticketCount: 16, ticketPrice: 50 },
  //     { ticketType: 'Bussiness', ticketCount: 13, ticketPrice: 200 },
  //     { ticketType: 'General Admission', ticketCount: 20, ticketPrice: 200 },
  //   ],
  // },
  // {
  //   id: 'J7NrtjDWJnXcbbVfT322n7fdG',
  //   name: 'Monster Jam',
  //   date: '2022-03-28T22:22',
  //   image: 'QmPVdPutqiNyJjd74eVpnfwUV4XZKLZBbBpyKqqDmampFy',
  //   ticketsSold: 0,
  //   ticketsCount: 40,
  //   eventDetails: [
  //     { ticketType: 'Vip', ticketCount: 6, ticketPrice: 400 },
  //     { ticketType: 'General', ticketCount: 3, ticketPrice: 50 },
  //     { ticketType: 'Bussiness', ticketCount: 9, ticketPrice: 200 },
  //     { ticketType: 'General Admission', ticketCount: 11, ticketPrice: 200 },
  //   ],
  // },
  // {
  //   id: 'J7NrtjDWJnXcbbVfddTn7iG',
  //   name: 'Monster Jam',
  //   date: '2022-03-28T22:22',
  //   image: 'QmPVdPutqiNyJjd74eVpnfwUV4XZKLZBbBpyKqqDmampFy',
  //   ticketsSold: 0,
  //   ticketsCount: 40,
  //   eventDetails: [
  //     { ticketType: 'Vip', ticketCount: 4, ticketPrice: 400 },
  //     { ticketType: 'General', ticketCount: 6, ticketPrice: 50 },
  //     { ticketType: 'Bussiness', ticketCount: 10, ticketPrice: 200 },
  //     { ticketType: 'General Admission', ticketCount: 20, ticketPrice: 200 },
  //   ],
  // },
];
