// Courtesy of https://twitter.com/lrgmnn/status/813635533658144768/
export const tickets = [
  {
    id: '4cCuxGrhmw1_ccYnuOIXk',
    name: 'Los Angeles Lakers',
    image: '',
    description: '',
    salePrice: 99,
    Tickets: 600,
    creatorName: 'Agoric',
  },
  {
    id: '4cCuxGrhmw1_ccYnuOIXk',
    name: 'Coachella 2022',
    image: '',
    description: '',
    salePrice: 99,
    Tickets: 600,
    creatorName: 'Agoric',
  },
  {
    id: 'ZnJ8MnhrMlYMkFcJk_pJP',
    name: 'Avril Lavigne Canada Tour 2022',
    image: '',
    description: '',
    salePrice: 99,
    Tickets: 600,
    creatorName: 'Agoric',
  },
  {
    id: 'fb8ApBtpIY1Ik9d62ZqFS',
    name: 'After Hours Till Dawn Tour',
    image: '',
    description: '',
    salePrice: 99,
    Tickets: 600,
    creatorName: 'Agoric',
  },
  {
    id: 'J7NrtjDWJnXcbbVfTn7iG',
    name: 'Monster Jam',
    image: '',
    description: '',
    salePrice: 99,
    Tickets: 600,
    creatorName: 'Agoric',
  },
];
